# Generated by Django 6.0.7 on 2026-07-21 14:33

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del Edificio')),
                ('direccion', models.CharField(max_length=300, verbose_name='Dirección')),
                ('ciudad', models.CharField(max_length=100)),
                ('provincia', models.CharField(max_length=100)),
                ('codigo_postal', models.CharField(max_length=10)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('categoria', models.CharField(choices=[('iglesia', 'Iglesia / Catedral'), ('museo', 'Museo'), ('monumento', 'Monumento'), ('casa_historica', 'Casa Histórica'), ('archivo', 'Archivo / Biblioteca'), ('otro', 'Otro Patrimonio')], default='monumento', max_length=20)),
                ('descripcion', models.TextField(blank=True, verbose_name='Descripción histórica')),
                ('anno_construccion', models.PositiveIntegerField(blank=True, null=True, verbose_name='Año de construcción')),
                ('proteccion_oficial', models.BooleanField(default=False, verbose_name='Protección oficial (Bien de Interés Cultural)')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='edificios/')),
                ('estado_general', models.CharField(choices=[('excelente', 'Excelente'), ('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('critico', 'Crítico')], default='regular', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('propietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='edificios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Edificio Patrimonial',
                'verbose_name_plural': 'Edificios Patrimoniales',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('contenido', models.TextField()),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('periodo_desde', models.DateField()),
                ('periodo_hasta', models.DateField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='informes/pdf/')),
                ('archivo_excel', models.FileField(blank=True, null=True, upload_to='informes/excel/')),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='informes', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Informe',
                'verbose_name_plural': 'Informes',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('admin', 'Administrador'), ('conservador', 'Conservador'), ('tecnico', 'Técnico'), ('visualizador', 'Visualizador')], default='visualizador', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20)),
                ('organizacion', models.CharField(blank=True, max_length=200)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('edificios_asignados', models.ManyToManyField(blank=True, related_name='usuarios_asignados', to='monitor.edificio')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuarios',
            },
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Sensor')),
                ('tipo', models.CharField(choices=[('temperatura', 'Temperatura'), ('humedad', 'Humedad'), ('vibracion', 'Vibración'), ('luz', 'Luz / Radiación UV'), ('co2', 'CO₂'), ('ruido', 'Ruido'), ('grieta', 'Monitor de Grietas'), ('presion', 'Presión Atmosférica')], max_length=20)),
                ('ubicacionDescripcion', models.CharField(help_text='Ej: "Nave lateral derecha, techos a 3m"', max_length=300, verbose_name='Ubicación en el edificio')),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('umbral_min', models.FloatField(blank=True, null=True, verbose_name='Umbral Mínimo')),
                ('umbral_max', models.FloatField(blank=True, null=True, verbose_name='Umbral Máximo')),
                ('unidad_medida', models.CharField(default='unidades', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_instalacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensores', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Sensor',
                'verbose_name_plural': 'Sensores',
                'ordering': ['edificio', 'tipo'],
            },
        ),
        migrations.CreateModel(
            name='Lectura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('valor', models.FloatField(verbose_name='Valor medido')),
                ('fecha_hora', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha y Hora')),
                ('es_alerta', models.BooleanField(default=False, verbose_name='Generó alerta')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lecturas', to='monitor.sensor')),
            ],
            options={
                'verbose_name': 'Lectura',
                'verbose_name_plural': 'Lecturas',
                'ordering': ['-fecha_hora'],
            },
        ),
        migrations.CreateModel(
            name='Alerta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo_alerta', models.CharField(choices=[('bajo', 'Bajo umbral'), ('alto', 'Sobre umbral')], max_length=10)),
                ('severidad', models.CharField(choices=[('info', 'Informativa'), ('warning', 'Advertencia'), ('critical', 'Crítica')], default='warning', max_length=10)),
                ('mensaje', models.TextField()),
                ('valor_detectado', models.FloatField()),
                ('resuelta', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_resolucion', models.DateTimeField(blank=True, null=True)),
                ('notas_resolucion', models.TextField(blank=True)),
                ('resuelta_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('lectura', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alertas', to='monitor.lectura')),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='monitor.sensor')),
            ],
            options={
                'verbose_name': 'Alerta',
                'verbose_name_plural': 'Alertas',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='SensorFoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='sensores/fotos/')),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='monitor.sensor')),
            ],
            options={
                'verbose_name': 'Foto del Sensor',
                'verbose_name_plural': 'Fotos de Sensores',
            },
        ),
    ]
