# Generated by Django 6.0.7 on 2026-07-21 15:15

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0002_auditlog_equipo_mantenimiento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionSMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_sid', models.CharField(blank=True, max_length=100, verbose_name='Twilio Account SID')),
                ('auth_token', models.CharField(blank=True, max_length=100, verbose_name='Twilio Auth Token')),
                ('numero_origen', models.CharField(blank=True, max_length=20, verbose_name='Número Twilio')),
                ('numeros_destino', models.TextField(blank=True, verbose_name='Números destino (uno por línea)')),
                ('activo', models.BooleanField(default=False)),
                ('alertas_criticas', models.BooleanField(default=True, verbose_name='Enviar alertas críticas por SMS')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Configuración SMS/WhatsApp',
                'verbose_name_plural': 'Configuraciones SMS/WhatsApp',
            },
        ),
        migrations.CreateModel(
            name='ChatMensaje',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mensajes', to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_mensajes', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Mensaje de Chat',
                'verbose_name_plural': 'Mensajes de Chat',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Logro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
                ('icono', models.CharField(choices=[('trophy', 'Trofeo'), ('star', 'Estrella'), ('fire', 'Fuego'), ('gem', 'Gema'), ('crown', 'Corona'), ('bolt', 'Rayo')], default='trophy', max_length=20)),
                ('puntos_necesarios', models.PositiveIntegerField()),
                ('color', models.CharField(default='#d4a853', max_length=7)),
                ('usuarios', models.ManyToManyField(blank=True, related_name='logros', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Logro',
                'verbose_name_plural': 'Logros',
                'ordering': ['puntos_necesarios'],
            },
        ),
        migrations.CreateModel(
            name='Notificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('mensaje', models.TextField()),
                ('tipo', models.CharField(choices=[('alerta', 'Alerta'), ('mantenimiento', 'Mantenimiento'), ('sistema', 'Sistema'), ('equipo', 'Equipo')], default='sistema', max_length=20)),
                ('leida', models.BooleanField(default=False)),
                ('url_destino', models.CharField(blank=True, max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificación',
                'verbose_name_plural': 'Notificaciones',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='PuntoGamificacion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(choices=[('resolver_alerta', 'Resolver Alerta'), ('crear_edificio', 'Crear Edificio'), ('crear_sensor', 'Crear Sensor'), ('registrar_lectura', 'Registrar Lectura'), ('generar_informe', 'Generar Informe'), ('login_diario', 'Login Diario')], max_length=20)),
                ('puntos', models.PositiveIntegerField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcion', models.CharField(blank=True, max_length=300)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puntos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Punto de Gamificación',
                'verbose_name_plural': 'Puntos de Gamificación',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='TimelineFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to='timeline/')),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_toma', models.DateField(default=django.utils.timezone.now)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_fotos', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Foto Timeline',
                'verbose_name_plural': 'Fotos Timeline',
                'ordering': ['-fecha_toma'],
            },
        ),
    ]
