# Generated by Django 6.0.7 on 2026-07-23 14:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0004_analisisia_certificadoblockchain_cumplimientolegal_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('archivo', models.CharField(max_length=500)),
                ('tipo', models.CharField(default='completo', max_length=20)),
                ('tamano_kb', models.FloatField(default=0)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='CalidadAire',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('co2', models.FloatField(default=0, verbose_name='CO2 (ppm)')),
                ('no2', models.FloatField(default=0, verbose_name='NO2 (ug/m3)')),
                ('pm25', models.FloatField(default=0, verbose_name='PM2.5 (ug/m3)')),
                ('pm10', models.FloatField(default=0, verbose_name='PM10 (ug/m3)')),
                ('o3', models.FloatField(default=0, verbose_name='O3 (ug/m3)')),
                ('calidad', models.CharField(default='buena', max_length=20)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calidad_aire', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Calidad del Aire',
                'verbose_name_plural': 'Calidad del Aire',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ChatMensajeIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('respuesta', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ia', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat IA',
                'verbose_name_plural': 'Chats IA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ComentarioEdificio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('texto', models.TextField()),
                ('rating', models.PositiveIntegerField(default=5)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('activo', models.BooleanField(default=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='GaleriaFoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('imagen_antes', models.ImageField(upload_to='galeria/antes/')),
                ('imagen_despues', models.ImageField(upload_to='galeria/despues/')),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_antes', models.DateField(blank=True, null=True)),
                ('fecha_despues', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galeria', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Galeria Antes/Despues',
                'verbose_name_plural': 'Galeria Antes/Despues',
            },
        ),
        migrations.CreateModel(
            name='MedicionRuido',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=200)),
                ('nivel_db', models.FloatField(verbose_name='Nivel en dB')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('latitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitud', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones_ruido', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Medicion de Ruido',
                'verbose_name_plural': 'Mediciones de Ruido',
                'ordering': ['-fecha'],
            },
        ),
    ]
