# Generated by Django 6.0.7 on 2026-07-23 15:18

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0005_backuplog_calidadaire_chatmensajeia_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnomaliaDetectada',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('temperatura', 'Anomalia de Temperatura'), ('humedad', 'Anomalia de Humedad'), ('vibracion', 'Anomalia de Vibracion'), ('estructural', 'Anomalia Estructural'), ('consumo', 'Anomalia de Consumo')], max_length=20)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('valor_esperado', models.FloatField(default=0)),
                ('valor_detectado', models.FloatField(default=0)),
                ('desviacion', models.FloatField(default=0)),
                ('gravedad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta')], max_length=10)),
                ('revisada', models.BooleanField(default=False)),
                ('fecha_deteccion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anomalias', to='monitor.edificio')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.sensor')),
            ],
            options={
                'verbose_name': 'Anomalia Detectada',
                'verbose_name_plural': 'Anomalias Detectadas',
                'ordering': ['-fecha_deteccion'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoEdificio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(choices=[('plano', 'Plano'), ('permiso', 'Permiso'), ('contrato', 'Contrato'), ('informe_tecnico', 'Informe Tecnico'), ('historico', 'Documento Historico'), ('fotografia', 'Fotografia'), ('otro', 'Otro')], max_length=20)),
                ('archivo', models.FileField(upload_to='documentos/')),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('fecha_documento', models.DateField(blank=True, null=True)),
                ('tamaño_kb', models.FloatField(default=0)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documentos', to='monitor.edificio')),
                ('subido_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['-fecha_subida'],
            },
        ),
        migrations.CreateModel(
            name='FormularioInspeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('fecha_inspeccion', models.DateField(default=django.utils.timezone.now)),
                ('resultado', models.CharField(choices=[('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('pendiente', 'Pendiente'), ('con_observaciones', 'Con Observaciones')], default='pendiente', max_length=20)),
                ('checklist', models.JSONField(default=list, verbose_name='Checklist items')),
                ('observaciones', models.TextField(blank=True)),
                ('firma_digital', models.TextField(blank=True, verbose_name='Firma digital (base64)')),
                ('foto_evidencia', models.ImageField(blank=True, null=True, upload_to='inspecciones/')),
                ('proxima_inspeccion', models.DateField(blank=True, null=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspecciones', to='monitor.edificio')),
                ('inspector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Inspeccion',
                'verbose_name_plural': 'Inspecciones',
                'ordering': ['-fecha_inspeccion'],
            },
        ),
        migrations.CreateModel(
            name='Herramienta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('categoria', models.CharField(max_length=100)),
                ('numero_serie', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('disponible', 'Disponible'), ('en_uso', 'En Uso'), ('mantenimiento', 'En Mantenimiento'), ('dada_baja', 'Dada de Baja')], default='disponible', max_length=20)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('fecha_compra', models.DateField(blank=True, null=True)),
                ('fecha_ultimo_mantenimiento', models.DateField(blank=True, null=True)),
                ('proximo_mantenimiento', models.DateField(blank=True, null=True)),
                ('costo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='herramientas/')),
                ('activo', models.BooleanField(default=True)),
                ('edificio_asignado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='herramientas', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Herramienta',
                'verbose_name_plural': 'Herramientas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RecomendacionIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('categoria', models.CharField(max_length=50)),
                ('confianza', models.FloatField(default=0)),
                ('accion_recomendada', models.TextField()),
                ('implementada', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recomendaciones', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Recomendacion IA',
                'verbose_name_plural': 'Recomendaciones IA',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='TimelineHistorico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('fecha_evento', models.DateField()),
                ('categoria', models.CharField(default='restauracion', max_length=50)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='timeline_historico/')),
                ('fuente', models.CharField(blank=True, max_length=300)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_historico', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Evento Historico',
                'verbose_name_plural': 'Timeline Historico',
                'ordering': ['fecha_evento'],
            },
        ),
        migrations.CreateModel(
            name='Voluntario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('habilidades', models.TextField(blank=True, verbose_name='Habilidades y experiencia')),
                ('disponibilidad', models.CharField(blank=True, max_length=100)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('pendiente', 'Pendiente')], default='pendiente', max_length=20)),
                ('horas_voluntariado', models.FloatField(default=0)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('edificios', models.ManyToManyField(blank=True, related_name='voluntarios', to='monitor.edificio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='voluntariados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Voluntario',
                'verbose_name_plural': 'Voluntarios',
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
