# Generated by Django 6.0.7 on 2026-07-24 06:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0006_anomaliadetectada_documentoedificio_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ComparativaCiudad',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ciudad', models.CharField(max_length=100)),
                ('edificio_tipo', models.CharField(max_length=100)),
                ('media_salud', models.FloatField(default=0)),
                ('media_sensores', models.IntegerField(default=0)),
                ('media_alertas', models.IntegerField(default=0)),
                ('total_edificios', models.IntegerField(default=0)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comparativa Ciudad',
                'verbose_name_plural': 'Comparativas Ciudad',
                'ordering': ['ciudad'],
            },
        ),
        migrations.CreateModel(
            name='ReporteAutomatico',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='semanal', max_length=20)),
                ('contenido', models.TextField()),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='reportes_automaticos/')),
                ('enviado', models.BooleanField(default=False)),
                ('fecha_generacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_envio', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Reporte Automatico',
                'verbose_name_plural': 'Reportes Automaticos',
                'ordering': ['-fecha_generacion'],
            },
        ),
        migrations.CreateModel(
            name='ConfiguracionIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('ar', 'العربية')], default='es', max_length=5)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='idioma_config', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuracion de Idioma',
                'verbose_name_plural': 'Configuraciones de Idioma',
            },
        ),
        migrations.CreateModel(
            name='MantenimientoPredictivo',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('probabilidad_fallo', models.FloatField(default=0, verbose_name='Probabilidad de fallo (%)')),
                ('dias_estimados', models.IntegerField(default=30, verbose_name='Dias hasta fallo estimado')),
                ('costo_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('accion_recomendada', models.TextField()),
                ('implementada', models.BooleanField(default=False)),
                ('fecha_prediccion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='predicciones_mantenimiento', to='monitor.edificio')),
                ('sensor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.sensor')),
            ],
            options={
                'verbose_name': 'Mantenimiento Predictivo',
                'verbose_name_plural': 'Mantenimientos Predictivos',
                'ordering': ['-probabilidad_fallo'],
            },
        ),
        migrations.CreateModel(
            name='ModoEmergencia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('motivo', models.TextField()),
                ('email_enviado', models.BooleanField(default=False)),
                ('pdf_generado', models.BooleanField(default=False)),
                ('fecha_activacion', models.DateTimeField(auto_now_add=True)),
                ('desactivado', models.BooleanField(default=False)),
                ('fecha_desactivacion', models.DateTimeField(blank=True, null=True)),
                ('activado_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modos_emergencia', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Modo Emergencia',
                'verbose_name_plural': 'Modos de Emergencia',
                'ordering': ['-fecha_activacion'],
            },
        ),
        migrations.CreateModel(
            name='RegistroROI',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('ahorro_energetico', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ahorro_multas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('ahorro_restauraciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('donaciones_recibidas', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('inversion_smartheritage', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_roi', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Registro ROI',
                'verbose_name_plural': 'Registros ROI',
                'ordering': ['-fecha'],
            },
        ),
    ]
