# Generated by Django 6.0.7 on 2026-07-24 07:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0007_comparativaciudad_reporteautomatico_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoriaGasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#dc3545', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Gasto',
                'verbose_name_plural': 'Categorias de Gasto',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CategoriaIngreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('color', models.CharField(default='#28a745', max_length=7)),
            ],
            options={
                'verbose_name': 'Categoria de Ingreso',
                'verbose_name_plural': 'Categorias de Ingreso',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('activo', 'Activo'), ('pasivo', 'Pasivo'), ('ingreso', 'Ingreso'), ('gasto', 'Gasto')], max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('activa', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Cuenta Contable',
                'verbose_name_plural': 'Cuentas Contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('emitted', 'Emitida'), ('received', 'Recibida')], default='emitted', max_length=10)),
                ('cliente_proveedor', models.CharField(max_length=200)),
                ('cliente_nif', models.CharField(blank=True, max_length=20)),
                ('cliente_direccion', models.TextField(blank=True)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('concepto', models.CharField(max_length=300)),
                ('base_imponible', models.DecimalField(decimal_places=2, max_digits=12)),
                ('porcentaje_iva', models.DecimalField(decimal_places=2, default=21, max_digits=5)),
                ('importe_iva', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviada', 'Enviada'), ('pagada', 'Pagada'), ('vencida', 'Vencida'), ('cancelada', 'Cancelada')], default='borrador', max_length=10)),
                ('fecha_emision', models.DateField()),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='facturas/pdfs/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facturas', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Factura',
                'verbose_name_plural': 'Facturas',
                'ordering': ['-fecha_emision'],
            },
        ),
        migrations.CreateModel(
            name='Gasto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('fecha', models.DateField()),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('pagado', models.BooleanField(default=False)),
                ('proveedor', models.CharField(blank=True, max_length=200)),
                ('proveedor_nif', models.CharField(blank=True, max_length=20)),
                ('forma_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('tarjeta', 'Tarjeta'), ('transferencia', 'Transferencia'), ('domiciliado', 'Domiciliado'), ('cheque', 'Cheque')], default='transferencia', max_length=15)),
                ('numero_factura_proveedor', models.CharField(blank=True, max_length=50)),
                ('deducible', models.BooleanField(default=False, verbose_name='Deducible de IRPF')),
                ('notas', models.TextField(blank=True)),
                ('archivo_adjunto', models.FileField(blank=True, null=True, upload_to='gastos/adjuntos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.categoriagasto')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gastos', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Gasto',
                'verbose_name_plural': 'Gastos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Ingreso',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('concepto', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12)),
                ('moneda', models.CharField(default='EUR', max_length=3)),
                ('fecha', models.DateField()),
                ('fecha_cobro', models.DateField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('cobrado', 'Cobrado'), ('cancelado', 'Cancelado')], default='pendiente', max_length=15)),
                ('cliente_nombre', models.CharField(blank=True, max_length=200)),
                ('cliente_email', models.EmailField(blank=True, max_length=254)),
                ('cliente_nif', models.CharField(blank=True, max_length=20)),
                ('recurrente', models.BooleanField(default=False)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.categoriaingreso')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingresos', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Ingreso',
                'verbose_name_plural': 'Ingresos',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Nomina',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('salario_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('complemento', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('bonus', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Bonus/Incentivos')),
                ('retenciones', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('seguridad_social', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('neto', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('periodo', models.CharField(max_length=20, verbose_name='Periodo (Ej: Enero 2025)')),
                ('fecha_pago', models.DateField()),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('pagada', 'Pagada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.edificio')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Nomina',
                'verbose_name_plural': 'Nominas',
                'ordering': ['-fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Presupuesto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=200)),
                ('monto_asignado', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monto_gastado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('periodo', models.CharField(choices=[('mensual', 'Mensual'), ('trimestral', 'Trimestral'), ('anual', 'Anual')], default='mensual', max_length=15)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('alerta_porcentaje', models.IntegerField(default=80, verbose_name='Alertar al % gastado')),
                ('activo', models.BooleanField(default=True)),
                ('categoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.categoriagasto')),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presupuestos', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Presupuesto',
                'verbose_name_plural': 'Presupuestos',
                'ordering': ['-fecha_inicio'],
            },
        ),
    ]
