# Generated by Django 6.0.7 on 2026-07-24 07:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0008_categoriagasto_categoriaingreso_cuentacontable_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificacionWhatsApp',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('telefono', models.CharField(max_length=20)),
                ('mensaje', models.TextField()),
                ('enviado', models.BooleanField(default=False)),
                ('error', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Notificacion WhatsApp',
                'verbose_name_plural': 'Notificaciones WhatsApp',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ChatAsistenteIA',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje_usuario', models.TextField()),
                ('respuesta_ia', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edificio_contexto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.edificio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_ia_historial', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Chat Asistente IA',
                'verbose_name_plural': 'Chats Asistente IA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('fecha_inicio', models.DateTimeField()),
                ('fecha_fin', models.DateTimeField()),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('completada', 'Completada'), ('cancelada', 'Cancelada'), ('reprogramada', 'Reprogramada')], default='programada', max_length=15)),
                ('recordatorio_horas', models.IntegerField(default=24, verbose_name='Recordatorio (horas antes)')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='monitor.edificio')),
                ('participantes', models.ManyToManyField(blank=True, related_name='citas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cita',
                'verbose_name_plural': 'Citas',
                'ordering': ['fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='ContratoDigital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('partes', models.TextField(help_text='Nombres de las partes involucradas, separados por coma')),
                ('condiciones', models.TextField()),
                ('monto_total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('enviado', 'Enviado'), ('firmado', 'Firmado'), ('vencido', 'Vencido'), ('cancelado', 'Cancelado')], default='borrador', max_length=10)),
                ('firma_contratista', models.TextField(blank=True, help_text='Base64 de la firma')),
                ('firma_empresa', models.TextField(blank=True, help_text='Base64 de la firma')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('archivo_pdf', models.FileField(blank=True, null=True, upload_to='contratos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contratos', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Contrato Digital',
                'verbose_name_plural': 'Contratos Digitales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='DigitalTwin',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo_3d_url', models.URLField(blank=True, help_text='URL del modelo GLB/GLTF')),
                ('estado_color', models.CharField(default='#28a745', max_length=7)),
                ('ultima_actualizacion', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('edificio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='digital_twin', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Digital Twin',
                'verbose_name_plural': 'Digital Twins',
            },
        ),
        migrations.CreateModel(
            name='FotoInspeccion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('imagen', models.ImageField(upload_to='inspeccion_ia/')),
                ('resultado_ia', models.CharField(blank=True, choices=[('ok', 'Sin problemas'), ('grietas', 'Grietas detectadas'), ('humedad', 'Humedad detectada'), ('dano_estructural', 'Dano estructural'), ('desgaste', 'Desgaste general')], max_length=20)),
                ('confianza_ia', models.FloatField(default=0)),
                ('detalles_ia', models.TextField(blank=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos_inspeccion', to='monitor.edificio')),
                ('subida_por', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Foto Inspeccion IA',
                'verbose_name_plural': 'Fotos Inspeccion IA',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='BitacoraObra',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('tipo', models.CharField(choices=[('inicio', 'Inicio de Obra'), ('avance', 'Avance'), ('problema', 'Problema Detectado'), ('solucion', 'Solucion Aplicada'), ('material', 'Material Recibido'), ('inspeccion', 'Inspeccion'), ('fin', 'Fin de Obra')], default='avance', max_length=15)),
                ('coste', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bitacora_obras', to='monitor.edificio')),
                ('fotos', models.ManyToManyField(blank=True, to='monitor.fotoinspeccion')),
            ],
            options={
                'verbose_name': 'Bitacora de Obra',
                'verbose_name_plural': 'Bitacoras de Obras',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ItemInventario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('categoria', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('cantidad', models.IntegerField(default=1)),
                ('estado', models.CharField(choices=[('bueno', 'Bueno'), ('regular', 'Regular'), ('malo', 'Malo'), ('deteriorado', 'Deteriorado')], default='bueno', max_length=15)),
                ('ubicacion', models.CharField(blank=True, max_length=200)),
                ('valor_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fecha_adquisicion', models.DateField(blank=True, null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='inventario/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventario', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Item de Inventario',
                'verbose_name_plural': 'Items de Inventario',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='TareaKanban',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('en_progreso', 'En Progreso'), ('revision', 'En Revision'), ('completada', 'Completada')], default='pendiente', max_length=15)),
                ('prioridad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('urgente', 'Urgente')], default='media', max_length=10)),
                ('fecha_limite', models.DateField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('orden', models.IntegerField(default=0)),
                ('asignado_a', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tareas_asignadas', to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tareas_kanban', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Tarea Kanban',
                'verbose_name_plural': 'Tareas Kanban',
                'ordering': ['orden', '-fecha_creacion'],
            },
        ),
    ]
