# Generated by Django 6.0.7 on 2026-07-24 07:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0009_notificacionwhatsapp_chatasistenteia_cita_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RolSistema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True)),
                ('puede_ver_edificios', models.BooleanField(default=True)),
                ('puede_editar_edificios', models.BooleanField(default=False)),
                ('puede_ver_alertas', models.BooleanField(default=True)),
                ('puede_resolver_alertas', models.BooleanField(default=False)),
                ('puede_ver_finanzas', models.BooleanField(default=False)),
                ('puede_editar_finanzas', models.BooleanField(default=False)),
                ('puede_ver_sensores', models.BooleanField(default=True)),
                ('puede_editar_sensores', models.BooleanField(default=False)),
                ('puede_ver_inventario', models.BooleanField(default=True)),
                ('puede_editar_inventario', models.BooleanField(default=False)),
                ('puede_aprobar', models.BooleanField(default=False)),
                ('puede_exportar', models.BooleanField(default=True)),
                ('puede_ver_reportes', models.BooleanField(default=True)),
                ('es_admin', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Rol del Sistema',
                'verbose_name_plural': 'Roles del Sistema',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='TextoMultiidioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=200, unique=True)),
                ('es', models.TextField(blank=True)),
                ('en', models.TextField(blank=True)),
                ('ar', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Texto Multiidioma',
                'verbose_name_plural': 'Textos Multiidioma',
                'ordering': ['clave'],
            },
        ),
        migrations.CreateModel(
            name='WebhookConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('evento', models.CharField(choices=[('alerta_nueva', 'Nueva Alerta'), ('alerta_resuelta', 'Alerta Resuelta'), ('mantenimiento', 'Nuevo Mantenimiento'), ('factura', 'Nueva Factura'), ('sensor_fallo', 'Fallo de Sensor')], max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('secreto', models.CharField(blank=True, max_length=100)),
                ('ultimo_envio', models.DateTimeField(blank=True, null=True)),
                ('exitoso', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Webhook',
                'verbose_name_plural': 'Webhooks',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='CalculadoraRestauracion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('area_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('costo_m2', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('mano_obra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('materiales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('permisos', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('imprevistos_pct', models.IntegerField(default=10, verbose_name='% Imprevistos')),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_calculo', models.DateTimeField(auto_now_add=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calculos_restauracion', to='monitor.edificio')),
            ],
            options={
                'verbose_name': 'Calculo de Restauracion',
                'verbose_name_plural': 'Calculos de Restauracion',
                'ordering': ['-fecha_calculo'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('modelo_tipo', models.CharField(blank=True, help_text='Modelo relacionado (ej: Alerta, Factura)', max_length=50)),
                ('modelo_id', models.CharField(blank=True, help_text='ID del objeto relacionado', max_length=100)),
                ('texto', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('editado', models.BooleanField(default=False)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mis_comentarios', to=settings.AUTH_USER_MODEL)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios_edificio', to='monitor.edificio')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='monitor.comentario')),
            ],
            options={
                'verbose_name': 'Comentario',
                'verbose_name_plural': 'Comentarios',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('widget_tipo', models.CharField(choices=[('alertas', 'Alertas Activas'), ('sensores', 'Estado Sensores'), ('finanzas', 'Resumen Financiero'), ('mantenimiento', 'Mantenimientos'), ('grafica_ingresos', 'Grafica Ingresos'), ('grafica_alertas', 'Grafica Alertas'), ('mapa', 'Mapa'), ('calendario', 'Calendario'), ('ultimas_acciones', 'Ultimas Acciones')], max_length=20)),
                ('titulo', models.CharField(max_length=100)),
                ('posicion', models.IntegerField(default=0)),
                ('ancho', models.IntegerField(default=6, help_text='Columnas (1-12)')),
                ('alto', models.IntegerField(default=3, help_text='Filas')),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dashboard_widgets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Widget del Dashboard',
                'verbose_name_plural': 'Widgets del Dashboard',
                'ordering': ['posicion'],
            },
        ),
        migrations.CreateModel(
            name='ExportacionLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('formato', models.CharField(choices=[('pdf', 'PDF'), ('excel', 'Excel'), ('csv', 'CSV'), ('json', 'JSON')], max_length=10)),
                ('modelo_tipo', models.CharField(max_length=50)),
                ('registros', models.IntegerField(default=0)),
                ('archivo', models.FileField(blank=True, null=True, upload_to='exportaciones/')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Exportacion',
                'verbose_name_plural': 'Logs de Exportacion',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='NotificacionPush',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('cuerpo', models.TextField()),
                ('url', models.URLField(blank=True)),
                ('leida', models.BooleanField(default=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notificaciones_push_real', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notificacion Push',
                'verbose_name_plural': 'Notificaciones Push',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Recordatorio',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('tipo', models.CharField(choices=[('mantenimiento', 'Mantenimiento'), ('inspeccion', 'Inspeccion'), ('pago', 'Pago'), ('vencimiento', 'Vencimiento'), ('reunion', 'Reunion'), ('personal', 'Personal')], default='personal', max_length=15)),
                ('fecha_recordatorio', models.DateTimeField()),
                ('leido', models.BooleanField(default=False)),
                ('enviado_email', models.BooleanField(default=False)),
                ('repetir', models.BooleanField(default=False)),
                ('intervalo_dias', models.IntegerField(default=0)),
                ('edificio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.edificio')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Recordatorio',
                'verbose_name_plural': 'Recordatorios',
                'ordering': ['fecha_recordatorio'],
            },
        ),
        migrations.CreateModel(
            name='PermisosUsuario',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notificaciones_email', models.BooleanField(default=True)),
                ('notificaciones_push', models.BooleanField(default=True)),
                ('notificaciones_whatsapp', models.BooleanField(default=False)),
                ('edificios_asignados', models.ManyToManyField(blank=True, related_name='edificios_permisos', to='monitor.edificio')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='permisos_sistema', to=settings.AUTH_USER_MODEL)),
                ('rol', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='monitor.rolsistema')),
            ],
            options={
                'verbose_name': 'Permisos de Usuario',
                'verbose_name_plural': 'Permisos de Usuarios',
            },
        ),
    ]
