# Generated by Django 6.0.7 on 2026-08-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0012_desafio_avatarusuario_camaravigilancia_carboncredit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='textomultiidioma',
            name='fr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='configuracionidioma',
            name='idioma',
            field=models.CharField(choices=[('es', 'Espanol'), ('en', 'English'), ('fr', 'Français'), ('ar', 'العربية')], default='es', max_length=5),
        ),
    ]

    TEXTOS_DEFAULT = {
        'nav_dashboard': ('Dashboard', 'Dashboard', 'Tableau de bord', 'لوحة التحكم'),
        'nav_mapa': ('Mapa', 'Map', 'Carte', 'الخريطة'),
        'nav_edificios': ('Edificios', 'Buildings', 'Bâtiments', 'المباني'),
        'nav_comparar': ('Comparar', 'Compare', 'Comparer', 'مقارنة'),
        'nav_vivo': ('Vivo', 'Live', 'Direct', 'مباشر'),
        'nav_alertas': ('Alertas', 'Alerts', 'Alertes', 'التنبيهات'),
        'nav_mas': ('Más', 'More', 'Plus', 'المزيد'),
        'nav_mis_puntos': ('Mis Puntos', 'My Points', 'Mes Points', 'نقاطي'),
        'nav_cerrar_sesion': ('Cerrar Sesión', 'Logout', 'Déconnexion', 'تسجيل الخروج'),
        'idioma_espanol': ('Español', 'Spanish', 'Espagnol', 'الإسبانية'),
        'idioma_ingles': ('Inglés', 'English', 'Anglais', 'الإنجليزية'),
        'idioma_frances': ('Francés', 'French', 'Français', 'الفرنسية'),
        'idioma_arabe': ('Árabe', 'Arabic', 'Arabe', 'العربية'),
        'nav_idioma': ('Idioma', 'Language', 'Langue', 'اللغة'),
        'nav_modo_oscuro': ('Modo Oscuro', 'Dark Mode', 'Mode Sombre', 'الوضع المظلم'),
    }

    def cargar_textos(apps, schema_editor):
        TextoMultiidioma = apps.get_model('monitor', 'TextoMultiidioma')
        for clave, valores in Migration.TEXTOS_DEFAULT.items():
            TextoMultiidioma.objects.update_or_create(
                clave=clave,
                defaults={'es': valores[0], 'en': valores[1], 'fr': valores[2], 'ar': valores[3]},
            )

    operations.append(migrations.RunPython(cargar_textos, migrations.RunPython.noop))
