# Generated by Django 6.0.7 on 2026-08-01 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monitor', '0013_idioma_frances'),
    ]

    operations = []

    TEXTOS_DEFAULT = {
        'menu_calendario': ('Calendario', 'Calendar', 'Calendrier', 'التقويم'),
        'menu_gamificacion': ('Gamificacion', 'Gamification', 'Gestion', 'المكافآت'),
        'menu_equipos': ('Equipos', 'Teams', 'Équipes', 'الفرق'),
        'menu_mantenimientos': ('Mantenimientos', 'Maintenance', 'Maintenance', 'الصيانة'),
        'menu_chatbot': ('Chatbot IA', 'Chatbot AI', 'Chatbot IA', 'روبوت الدردشة'),
        'menu_galeria': ('Galeria Antes/Despues', 'Before/After Gallery', 'Galerie Avant/Après', 'معرض قبل وبعد'),
        'menu_ranking': ('Ranking Global', 'Global Ranking', 'Classement Mondial', 'التصنيف العالمي'),
        'menu_dashboard_energia': ('Dashboard Energia', 'Energy Dashboard', 'Tableau de Bord Énergétique', 'لوحة طاقة'),
        'menu_dashboard_seguros': ('Dashboard Seguros', 'Insurance Dashboard', 'Tableau de Bord Assurances', 'لوحة التأمينات'),
        'menu_dashboard_legal': ('Dashboard Legal', 'Legal Dashboard', 'Tableau de Bord Juridique', 'لوحة قانونية'),
        'menu_mapa_reportes': ('Mapa Reportes', 'Reports Map', 'Carte des Rapports', 'خريطة التقارير'),
        'menu_analisis_ia': ('Analisis IA', 'AI Analysis', 'Analyse IA', 'تحليل ذكاء اصطناعي'),
        'menu_predicciones': ('Predicciones ML', 'ML Predictions', 'Prédictions ML', 'توقعات التعلم الآلي'),
        'menu_donaciones': ('Donaciones', 'Donations', 'Dons', 'التبرعات'),
        'menu_reportes_ciudadanos': ('Reportes Ciudadanos', 'Citizen Reports', 'Rapports Citoyens', 'تقارير المواطنين'),
        'menu_seguros': ('Seguros', 'Insurance', 'Assurances', 'التأمينات'),
        'menu_energia': ('Energia', 'Energy', 'Energie', 'الطاقة'),
        'menu_cumplimiento_legal': ('Cumplimiento Legal', 'Legal Compliance', 'Conformité Légale', 'الامتثال القانوني'),
        'menu_blockchain': ('Blockchain', 'Blockchain', 'Blockchain', 'سلسلة الكتل'),
        'menu_tours_virtuales': ('Tours Virtuales', 'Virtual Tours', 'Visites Virtuelles', 'الجولات الافتراضية'),
        'menu_eventos': ('Eventos', 'Events', 'Événements', 'الفعاليات'),
        'menu_tienda': ('Tienda', 'Store', 'Boutique', 'المتجر'),
        'menu_tareas_pendientes': ('Tareas Pendientes', 'Pending Tasks', 'Tâches en Attente', 'المهام المعلقة'),
        'menu_dashboard_inversores': ('Dashboard Inversores', 'Investors Dashboard', 'Tableau de Bord Investisseurs', 'لوحة المستثمرين'),
        'menu_comparativa_periodos': ('Comparativa Periodos', 'Period Comparison', 'Comparaison Périodes', 'مقارنة الفترات'),
        'menu_configurar_email': ('Configurar Email', 'Configure Email', 'Configurer Email', 'إعداد البريد الإلكتروني'),
        'menu_anomalias_ia': ('Anomalias IA', 'AI Anomalies', 'Anomalies IA', 'البطرية الذكاء الاصطناعي'),
        'menu_herramientas': ('Herramientas', 'Tools', 'Outils', 'الأدوات'),
        'menu_portal_educativo': ('Portal Educativo', 'Educational Portal', 'Portail Éducatif', 'البوابة التعليمية'),
        'menu_voluntarios': ('Voluntarios', 'Volunteers', 'Bénévoles', 'المتطوعين'),
        'menu_reportes_automaticos': ('Reportes Automaticos', 'Automatic Reports', 'Rapports Automatiques', 'التقارير الآلية'),
        'menu_mantenimiento_predictivo': ('Mantenimiento Predictivo', 'Predictive Maintenance', 'Maintenance Prédictive', 'صيانة تنبؤية'),
        'menu_comparativa_ciudades': ('Comparativa Ciudades', 'Cities Comparison', 'Comparaison Villes', 'مقارنة المدن'),
        'menu_resumen_diario': ('Enviar Resumen Diario', 'Send Daily Summary', 'Envoyer le Relevé Quotidien', 'إرسال الملخص اليومي'),
        'menu_panel_financiero': ('Panel Financiero', 'Financial Panel', 'Tableau Financier', 'لوحة مالية'),
        'menu_ingresos': ('Ingresos', 'Income', 'Revenus', 'الدخل'),
        'menu_gastos': ('Gastos', 'Expenses', 'Dépenses', 'النفقات'),
        'menu_facturas': ('Facturas', 'Invoices', 'Factures', 'الفواتير'),
        'menu_nominas': ('Nominas', 'Payrolls', 'Bulletins de Paie', 'الرواتب'),
        'menu_presupuestos': ('Presupuestos', 'Budgets', 'Budgets', 'الميزانيات'),
        'menu_cuentas_contables': ('Cuentas Contables', 'Accounting Accounts', 'Comptes Comptables', 'الحسابات المحاسبية'),
        'menu_notificaciones_push': ('Notificaciones Push', 'Push Notifications', 'Notifications Push', 'إشعارات فورية'),
        'menu_backup': ('Backup', 'Backup', 'Sauvegarde', 'نسخ احتياطي'),
        'menu_sms': ('SMS/WhatsApp', 'SMS/WhatsApp', 'SMS/WhatsApp', 'SMS/WhatsApp'),
        'menu_audit_log': ('Audit Log', 'Audit Log', 'Journal d Audit', 'سجل التدقيق'),
        'menu_asistente_ia': ('Asistente IA', 'AI Assistant', 'Assistant IA', 'مساعد الذكاء الاصطناعي'),
        'menu_kanban': ('Kanban Tareas', 'Kanban Tasks', 'Tâches Kanban', 'مهام كانبان'),
        'menu_mapa_global': ('Mapa Global', 'Global Map', 'Carte Mondiale', 'الخريطة العالمية'),
        'menu_citas': ('Citas', 'Appointments', 'Rendez-vous', 'المواعيد'),
        'menu_fotos_ia': ('Fotos IA', 'AI Photos', 'Photos IA', 'صور بالذكاء الاصطناعي'),
        'menu_contratos': ('Contratos', 'Contracts', 'Contrats', 'العقود'),
        'menu_inventario': ('Inventario', 'Inventory', 'Inventaire', 'المخزون'),
        'menu_bitacora': ('Bitacora Obras', 'Work Log', 'Journal de Chantier', 'سجل الأعمال'),
        'menu_whatsapp': ('WhatsApp', 'WhatsApp', 'WhatsApp', 'WhatsApp'),
        'menu_swagger': ('Swagger API Docs', 'Swagger API Docs', 'Docs API Swagger', 'وثائق API سواغر'),
        'menu_redoc': ('ReDoc API', 'ReDoc API', 'ReDoc API', 'وثائق API ريدوك'),
        'nav_proxima_salat': ('PROXIMA SALAT', 'NEXT PRAYER', 'PRIERE SUIVANTE', 'الصلاة القادمة'),
    }

    def cargar_textos_navbar(apps, schema_editor):
        TextoMultiidioma = apps.get_model('monitor', 'TextoMultiidioma')
        for clave, valores in Migration.TEXTOS_DEFAULT.items():
            TextoMultiidioma.objects.update_or_create(
                clave=clave,
                defaults={'es': valores[0], 'en': valores[1], 'fr': valores[2], 'ar': valores[3]},
            )

    operations = [
        migrations.RunPython(cargar_textos_navbar, migrations.RunPython.noop),
    ]
