from django.urls import path
from . import views

app_name = 'monitor'

urlpatterns = [
    path('', views.dashboard, name='dashboard'),
    path('login/', views.login_view, name='login'),
    path('register/', views.register_view, name='register'),
    path('logout/', views.logout_view, name='logout'),

    path('mapa/', views.mapa_global, name='mapa_global'),
    path('comparativa/', views.comparativa, name='comparativa'),
    path('tiempo-real/', views.dashboard_tiempo_real, name='dashboard_tiempo_real'),
    path('audit-log/', views.audit_log, name='audit_log'),
    path('calendario/', views.calendario, name='calendario'),
    path('notificaciones/', views.notificaciones_view, name='notificaciones'),
    path('notificaciones/<uuid:pk>/leer/', views.marcar_notificacion_leida, name='marcar_notificacion_leida'),
    path('gamificacion/', views.gamificacion_view, name='gamificacion'),
    path('sms-config/', views.sms_config_view, name='sms_config'),

    path('edificios/', views.edificio_list, name='edificio_list'),
    path('edificios/crear/', views.edificio_create, name='edificio_create'),
    path('edificios/<uuid:pk>/', views.edificio_detail, name='edificio_detail'),
    path('edificios/<uuid:pk>/editar/', views.edificio_update, name='edificio_update'),
    path('edificios/<uuid:pk>/eliminar/', views.edificio_delete, name='edificio_delete'),
    path('edificios/<uuid:edificio_pk>/informes/crear/', views.informe_create, name='informe_create'),
    path('edificios/<uuid:edificio_pk>/exportar/excel/', views.exportar_excel, name='exportar_excel'),
    path('edificios/<uuid:edificio_pk>/exportar/csv/', views.exportar_csv, name='exportar_csv'),
    path('edificios/<uuid:edificio_pk>/importar/', views.importar_csv, name='importar_csv'),
    path('edificios/<uuid:edificio_pk>/chat/', views.chat_view, name='chat_view'),
    path('edificios/<uuid:edificio_pk>/timeline/', views.timeline_view, name='timeline_view'),
    path('edificios/<uuid:edificio_pk>/mantenimientos/crear/', views.mantenimiento_create, name='mantenimiento_create'),

    path('edificios/<uuid:edificio_pk>/sensores/crear/', views.sensor_create, name='sensor_create'),
    path('sensores/<uuid:pk>/', views.sensor_detail, name='sensor_detail'),
    path('sensores/<uuid:pk>/editar/', views.sensor_update, name='sensor_update'),
    path('sensores/<uuid:pk>/eliminar/', views.sensor_delete, name='sensor_delete'),
    path('sensores/<uuid:sensor_pk>/lecturas/crear/', views.lectura_create, name='lectura_create'),

    path('alertas/', views.alerta_list, name='alerta_list'),
    path('alertas/<uuid:pk>/resolver/', views.alerta_resolver, name='alerta_resolver'),

    path('informes/<uuid:pk>/', views.informe_detail, name='informe_detail'),

    path('equipos/', views.equipo_list, name='equipo_list'),
    path('equipos/crear/', views.equipo_create, name='equipo_create'),
    path('equipos/<uuid:pk>/', views.equipo_detail, name='equipo_detail'),

    path('mantenimientos/', views.mantenimiento_list, name='mantenimiento_list'),

    path('edificios/<uuid:edificio_pk>/analisis-ia/', views.analisis_ia_create, name='analisis_ia_create'),
    path('analisis-ia/', views.analisis_ia_list, name='analisis_ia_list'),
    path('analisis-ia/<uuid:pk>/', views.analisis_ia_detail, name='analisis_ia_detail'),

    path('edificios/<uuid:edificio_pk>/predicciones/', views.predicciones_create, name='predicciones_create'),
    path('predicciones/', views.predicciones_list, name='predicciones_list'),

    path('edificios/<uuid:edificio_pk>/donaciones/', views.donacion_create, name='donacion_create'),
    path('donaciones/', views.donacion_list, name='donacion_list'),

    path('edificios/<uuid:edificio_pk>/reportes/', views.reporte_ciudadano_create, name='reporte_ciudadano_create'),
    path('reportes/', views.reporte_ciudadano_list, name='reporte_ciudadano_list'),
    path('reportes/<uuid:pk>/responder/', views.reporte_ciudadano_responder, name='reporte_ciudadano_responder'),

    path('edificios/<uuid:edificio_pk>/seguros/', views.seguro_create, name='seguro_create'),
    path('seguros/', views.seguro_list, name='seguro_list'),

    path('edificios/<uuid:edificio_pk>/energia/', views.eficiencia_energetica_create, name='eficiencia_energetica_create'),
    path('energia/', views.eficiencia_energetica_list, name='eficiencia_energetica_list'),

    path('edificios/<uuid:edificio_pk>/legal/', views.cumplimiento_legal_create, name='cumplimiento_legal_create'),
    path('legal/', views.cumplimiento_legal_list, name='cumplimiento_legal_list'),

    path('edificios/<uuid:edificio_pk>/blockchain/', views.certificado_blockchain_create, name='certificado_blockchain_create'),
    path('blockchain/', views.certificado_blockchain_list, name='certificado_blockchain_list'),

    path('tours/', views.tour_virtual_list, name='tour_virtual_list'),
    path('tours/<uuid:pk>/', views.tour_virtual_view, name='tour_virtual_view'),

    path('edificios/<uuid:edificio_pk>/eventos/', views.evento_create, name='evento_create'),
    path('eventos/', views.evento_list, name='evento_list'),
    path('eventos/<uuid:pk>/participar/', views.evento_participar, name='evento_participar'),

    path('edificios/<uuid:edificio_pk>/tienda/', views.tienda_create, name='tienda_create'),
    path('tienda/', views.tienda_list, name='tienda_list'),

    path('chatbot/', views.chatbot_ia, name='chatbot_ia'),
    path('galeria/', views.galeria_list, name='galeria_list'),
    path('edificios/<uuid:edificio_pk>/galeria/', views.galeria_create, name='galeria_create'),
    path('edificios/<uuid:edificio_pk>/comentar/', views.comentario_create, name='comentario_create'),
    path('ranking/', views.ranking_global, name='ranking_global'),
    path('dashboard-energia/', views.dashboard_energia, name='dashboard_energia'),
    path('dashboard-seguros/', views.dashboard_seguros, name='dashboard_seguros'),
    path('dashboard-legal/', views.dashboard_legal, name='dashboard_legal'),
    path('notificaciones-push/', views.notificaciones_push_config, name='notificaciones_push'),
    path('backup/', views.backup_view, name='backup'),
    path('mapa-reportes/', views.mapa_reportes, name='mapa_reportes'),

    path('api/sensor/<uuid:sensor_pk>/lecturas/', views.api_ultimas_lecturas, name='api_lecturas'),
    path('api/edificio/<uuid:edificio_pk>/resumen/', views.api_resumen_edificio, name='api_resumen'),

    path('edificios/<uuid:pk>/visor-3d/', views.visor_3d, name='visor_3d'),
    path('edificios/<uuid:pk>/mapa-calor/', views.mapa_calor, name='mapa_calor'),
    path('edificios/<uuid:pk>/huella-co2/', views.huella_co2, name='huella_co2'),
    path('edificios/<uuid:edificio_pk>/documentos/', views.documento_list, name='documento_list'),
    path('herramientas/', views.herramienta_list, name='herramienta_list'),
    path('herramientas/crear/', views.herramienta_create, name='herramienta_create'),
    path('edificios/<uuid:edificio_pk>/inspecciones/', views.inspeccion_list, name='inspeccion_list'),
    path('edificios/<uuid:edificio_pk>/inspecciones/crear/', views.inspeccion_create, name='inspeccion_create'),
    path('edificios/<uuid:pk>/timeline-historico/', views.timeline_historico_list, name='timeline_historico_list'),
    path('edificios/<uuid:pk>/timeline-historico/crear/', views.timeline_historico_create, name='timeline_historico_create'),
    path('edificios/<uuid:pk>/recomendaciones/', views.recomendaciones_ia, name='recomendaciones_ia'),
    path('anomalias/', views.anomalias_list, name='anomalias_list'),
    path('edificios/<uuid:pk>/analisis-predictivo/', views.analisis_predictivo_avanzado, name='analisis_predictivo_avanzado'),
    path('portal-educativo/', views.portal_educativo, name='portal_educativo'),
    path('voluntarios/', views.voluntarios_list, name='voluntarios_list'),
    path('voluntarios/registro/', views.voluntario_register, name='voluntario_register'),

    path('tareas-pendientes/', views.tareas_pendientes, name='tareas_pendientes'),
    path('edificios/<uuid:pk>/generar-pdf/', views.generar_pdf, name='generar_pdf'),
    path('edificios/<uuid:pk>/generar-qr/', views.generar_qr, name='generar_qr'),
    path('dashboard-inversores/', views.dashboard_inversores, name='dashboard_inversores'),
    path('comparativa-periodos/', views.comparativa_periodos, name='comparativa_periodos'),

    path('configurar-email/', views.configurar_email, name='configurar_email'),
    path('enviar-email-test/', views.enviar_email_test, name='enviar_email_test'),
    path('alertas/<uuid:pk>/enviar-email/', views.enviar_alerta_email, name='enviar_alerta_email'),

    path('reportes-automaticos/', views.reportes_automaticos, name='reportes_automaticos'),
    path('generar-reporte-semanal/', views.generar_reporte_semanal, name='generar_reporte_semanal'),
    path('mantenimiento-predictivo/', views.mantenimiento_predictivo, name='mantenimiento_predictivo'),
    path('edificios/<uuid:pk>/crear-prediccion/', views.crear_prediccion, name='crear_prediccion'),
    path('edificios/<uuid:pk>/calculadora-roi/', views.calculadora_roi, name='calculadora_roi'),
    path('cambiar-idioma/', views.cambiar_idioma, name='cambiar_idioma'),
    path('resumen-diario/', views.resumen_diario, name='resumen_diario'),
    path('comparativa-ciudades/', views.comparativa_ciudades, name='comparativa_ciudades'),
    path('edificios/<uuid:pk>/modo-emergencia/', views.modo_emergencia, name='modo_emergencia'),

    path('panel-financiero/', views.panel_financiero, name='panel_financiero'),
    path('ingresos/', views.ingreso_list, name='ingreso_list'),
    path('edificios/<uuid:edificio_pk>/ingresos/crear/', views.ingreso_create, name='ingreso_create'),
    path('gastos/', views.gasto_list, name='gasto_list'),
    path('edificios/<uuid:edificio_pk>/gastos/crear/', views.gasto_create, name='gasto_create'),
    path('facturas/', views.factura_list, name='factura_list'),
    path('edificios/<uuid:edificio_pk>/facturas/crear/', views.factura_create, name='factura_create'),
    path('facturas/<uuid:pk>/pdf/', views.factura_pdf, name='factura_pdf'),
    path('facturas/<uuid:pk>/estado/', views.factura_estado, name='factura_estado'),
    path('nominas/', views.nomina_list, name='nomina_list'),
    path('nominas/crear/', views.nomina_create, name='nomina_create'),
    path('nominas/<uuid:pk>/estado/', views.nomina_estado, name='nomina_estado'),
    path('presupuestos/', views.presupuesto_list, name='presupuesto_list'),
    path('edificios/<uuid:edificio_pk>/presupuestos/crear/', views.presupuesto_create, name='presupuesto_create'),
    path('cuentas-contables/', views.cuenta_contable_list, name='cuenta_contable_list'),
    path('cuentas-contables/crear/', views.cuenta_contable_create, name='cuenta_contable_create'),

    path('chat-ia/', views.chat_asistente_ia, name='chat_asistente_ia'),
    path('edificios/<uuid:pk>/digital-twin/', views.digital_twin_view, name='digital_twin'),
    path('fotos-inspeccion/', views.foto_inspeccion_list, name='foto_inspeccion_list'),
    path('edificios/<uuid:edificio_pk>/fotos-inspeccion/crear/', views.foto_inspeccion_create, name='foto_inspeccion_create'),
    path('citas/', views.cita_list, name='cita_list'),
    path('edificios/<uuid:edificio_pk>/citas/crear/', views.cita_create, name='cita_create'),
    path('kanban/', views.kanban_view, name='kanban'),
    path('kanban/tarea/crear/', views.tarea_create, name='tarea_create'),
    path('kanban/tarea/<uuid:pk>/estado/', views.tarea_estado, name='tarea_estado'),
    path('mapa-global/', views.mapa_global, name='mapa_global'),
    path('backup/', views.backup_view, name='backup_detail'),
    path('whatsapp/', views.whatsapp_config, name='whatsapp_config'),
    path('contratos/', views.contrato_list, name='contrato_list'),
    path('edificios/<uuid:edificio_pk>/contratos/crear/', views.contrato_create, name='contrato_create'),
    path('inventario/', views.inventario_list, name='inventario_list'),
    path('edificios/<uuid:edificio_pk>/inventario/crear/', views.inventario_create, name='inventario_create'),
    path('bitacora/', views.bitacora_list, name='bitacora_list'),
    path('edificios/<uuid:edificio_pk>/bitacora/crear/', views.bitacora_create, name='bitacora_create'),

    path('rbac/', views.rbac_view, name='rbac'),
    path('rbac/rol/crear/', views.rol_create, name='rol_create'),
    path('rbac/permiso/crear/', views.permiso_create, name='permiso_create'),
    path('buscador/', views.buscador_global, name='buscador_global'),
    path('busqueda-avanzada/', views.busqueda_avanzada_view, name='busqueda_avanzada'),
    path('edificios/<uuid:edificio_pk>/comentarios/', views.comentarios_view, name='comentarios'),
    path('recordatorios/', views.recordatorios_view, name='recordatorios'),
    path('recordatorios/<uuid:pk>/marcar/', views.recordatorio_marcar, name='recordatorio_marcar'),
    path('edificios/<uuid:edificio_pk>/calculadora-restauracion/', views.calculadora_restauracion_view, name='calculadora_restauracion'),
    path('exportar-multiples/', views.exportar_multiples_view, name='exportar_multiples'),
    path('webhooks/', views.webhooks_view, name='webhooks'),
    path('dashboard-personalizado/', views.dashboard_personalizado_view, name='dashboard_personalizado'),
    path('idiomas/', views.idiomas_view, name='idiomas'),
    path('simulador-iot/', views.simulador_iot, name='simulador_iot'),
    path('api/simulador-iot/', views.simulador_iot_stream, name='simulador_iot_stream'),

    path('confirmar-email/<uuid:token_uuid>/', views.confirmar_email_view, name='confirmar_email'),
    path('reenviar-confirmacion/', views.resend_confirmation_view, name='resend_confirmation'),
    path('mfa/setup/', views.mfa_setup_view, name='mfa_setup'),
    path('mfa/verificar-setup/', views.mfa_verify_setup_view, name='mfa_verify_setup'),
    path('mfa/desactivar/', views.mfa_disable_view, name='mfa_disable'),
    path('mfa/verify/', views.mfa_verify_view, name='mfa_verify'),

    path('cotizaciones/', views.cotizacion_list, name='cotizacion_list'),
    path('cotizaciones/crear/', views.cotizacion_create, name='cotizacion_create'),
    path('cotizaciones/<uuid:cotizacion_pk>/', views.cotizacion_detail, name='cotizacion_detail'),
    path('cotizaciones/<uuid:cotizacion_pk>/editar/', views.cotizacion_edit, name='cotizacion_edit'),
    path('cotizaciones/<uuid:cotizacion_pk>/enviar/', views.cotizacion_enviar, name='cotizacion_enviar'),
    path('cotizaciones/<uuid:cotizacion_pk>/pdf/', views.cotizacion_pdf, name='cotizacion_pdf'),
    path('cotizacion/publica/<uuid:token_uuid>/', views.cotizacion_publica_view, name='cotizacion_publica'),

    # --- FUNCIONALIDADES INNOVADORAS ---
    path('time-machine/<uuid:pk>/', views.time_machine_view, name='time_machine'),
    path('time-machine/<uuid:pk>/procesar/', views.time_machine_procesar_view, name='time_machine_procesar'),
    path('twin-3d/<uuid:pk>/', views.digital_twin_3d_view, name='digital_twin_3d'),
    path('api/twin-interaccion/', views.api_twin_interaccion, name='api_twin_interaccion'),
    path('simulador-desastres/<uuid:pk>/', views.simulador_desastres_view, name='simulador_desastres'),
    path('patrimonio-vivo/', views.patrimonio_vivo_view, name='patrimonio_vivo'),
    path('patrimonio-vivo/camara/crear/<uuid:edificio_pk>/', views.camara_create_view, name='camara_create'),
    path('nft-marketplace/', views.nft_marketplace_view, name='nft_marketplace'),
    path('nft/crear/<uuid:edificio_pk>/', views.nft_create_view, name='nft_create'),
    path('nft/<uuid:pk>/', views.nft_detalle_view, name='nft_detalle'),
    path('smart-contracts/<uuid:edificio_pk>/', views.smart_contract_view, name='smart_contracts'),
    path('hito/<uuid:pk>/completar/', views.hito_completar_view, name='hito_completar'),
    path('carbon-credits/', views.carbon_credits_view, name='carbon_credits'),
    path('dna/<uuid:pk>/', views.dna_edificio_view, name='dna_edificio'),
    path('ai-guardian/', views.ai_guardian_view, name='ai_guardian'),
    path('tour-vr/<uuid:pk>/', views.tour_vr_view, name='tour_vr'),
    path('tour-vr/<uuid:pk>/visitar/', views.tour_vr_visita_view, name='tour_vr_visita'),
    path('desafios/', views.desafios_view, name='desafios'),
    path('desafios/<uuid:pk>/progreso/', views.desafio_progreso_view, name='desafio_progreso'),
    path('desafios/crear/', views.desafio_crear_view, name='desafio_crear'),
]
